### ISSUE TITLE
Some doubts and questions.

### ISSUE THREAD

**Issue by jpmelnik** [VulcanJS/Vulcan#1638]
Hi everybody.

I'm starting to do an administration app and I have some questions:

1) MongoDB is Part of VulcanJS? Can I use RethinkDB?
2) Offline Application is supported?
3) Can I use redux-form?
4) Whats server is recommended for deployments?
5) MeteorJS is the core of VulcanJS?
6) Can I test my application with mocha, jest or other test framework?
7) I'm considering support for mobile, Can I use React Native?

Can someone give me another recommendation?

Thanks.

**Comment by SachaG** [comment]
Great questions!

1. MongoDB is only required for the Users collection, since we're still using Meteor's user accounts system. You can use RethinkDB for all other collections, although you'll miss out on some of the nicer features of Vulcan. Maybe we can improve RethinkDB support though.

2. This depends on Apollo. There are some [threads](https://github.com/apollographql/apollo-client/issues/424) about it but I haven't looked into it too much yet. 

3. Vulcan has its own form package, but since Vulcan is using Redux anyway (as part of Apollo) it would make sense to integrate Redux-Form with it somehow. 

4. You can either use [Galaxy](http://galaxy.meteor.com) or else Digital Ocean with [Meteor Up](https://github.com/zodern/meteor-up).

5. Yes, although it only serves for the build system and the user accounts system. 

6. Yes.

7. I haven't tried myself, but I don't see any reason why not.
