### ISSUE TITLE
SyncedCron: scheduled "scheduleNewsletter" next run @Invalid Date

### ISSUE THREAD

**Issue by publu** [VulcanJS/Vulcan#1701]
I'm getting this error coming from a fresh install

`  "newsletterProvider": "mailchimp",
    "mailchimp":
    {
        "apiKey": "",
        "listId": "",
        "fromName": "",
        "fromEmail": ""
    },
    "newsletterFrequency": [1, 2, 3, 4, 5, 6, 7],
    "newsletterTime": "04:20",
    "newsletterExcerptLength": 20,
    "enableNewsletterInDev":true,
     "enableNewsletter": true,
`

Is there something wrong with the newsletterTime?

**Comment by publu** [comment]
```
I20170811-16:12:46.774(-5) (percolatestudio_synced-cron.js:84) SyncedCron: scheduled "checkScheduledPosts" next run @Fri Aug 11 2017 16:20:00 GMT-0500 (CDT)
I20170811-16:12:46.776(-5)? frequency: [object Object]
I20170811-16:12:46.778(-5)? serverTimeString: 00:0-40
I20170811-16:12:46.793(-5) (percolatestudio_synced-cron.js:84) SyncedCron: scheduled "scheduleNewsletter" next run @Invalid Date
```

**Comment by publu** [comment]
😐
newsletterTime in settings.json was setup with an array which causes something to mess up. Removing the variable from settings.json fixes it but removes the ability to configure the newsletter.

**Comment by valgalin** [comment]
Hi @publu , If I'm not mistaken, this was recently fixed in devel branch. Please see details here:

https://github.com/VulcanJS/Vulcan/commit/1fdee1025fd9745193128d40d2e8dd02378ccf6b

I just tried running the devel in local, and scheduleNewsletter is working fine with a correct time and date, and without the @Invalid Date warning.
