### ISSUE TITLE
Warning: Modal: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

### ISSUE THREAD

**Issue by c316** [VulcanJS/Vulcan#1706]
When I attempt to use ```Components.ModalTrigger``` in this context (from the Movies example)

```
{Movies.options.mutations.edit.check(currentUser, movie) ?
      <Components.ModalTrigger label="Edit Movie">
        <MilesEditForm currentUser={currentUser} documentId={movie._id} />
      </Components.ModalTrigger>
      : null
    }
```

I get this error message in the console 

```
Warning: Modal: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```

**Comment by SachaG** [comment]
You can probably ignore it for now.

**Comment by c316** [comment]
I should have mentioned that no modal opens either.

On Aug 15, 2017 1:35 AM, "Sacha Greif" <notifications@github.com> wrote:

You can probably ignore it for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VulcanJS/Vulcan/issues/1706#issuecomment-322388516>,
or mute
the thread

**Comment by SachaG** [comment]
Might be related to https://github.com/twbs/bootstrap/issues/21876#issuecomment-276181539

Modal popups won't work with anything above bootstrap alpha.5 currently.

**Comment by eric-burel** [comment]
Hi, maybe this should be documented, because installing last version of Bootstrap (so alpha 6 currently) is quite a natural reflex when building an app.

**Comment by MHerszak** [comment]
Just a note: Choosing a frontend library could become a personal choice. I am using Reactstrap. What I am trying to say is, ModalTrigger, Alert.. (all dependencies to react-bootstrap) need to be taken out of the core into a 'bootstrap package' because it will decrease its usability for other react apps. Something that could be documented (?known issues, ?custom components) is that you could use your own package and frontend and just `replaceComponent('ModalTrigger', CustomModalTrigger);`. I am not sure how much of a problem this would be for other devs. A solution could be to take out a component at a time, or just release a react-bootstrap package for Vulcan 2.0?

**Comment by SachaG** [comment]
It wouldn't be that hard to just rewrite the Modal component in a way that doesn't use any third-party libraries. 

Or we could also just switch to Reactstrap, since it works with Bootstrap 4.
