### ISSUE TITLE
Install without cloning?

### ISSUE THREAD

**Issue by mattbrunetti** [VulcanJS/Vulcan#1725]
Sorry if this seems like a silly question, but

Is it possible to install without cloning this whole project (as it instructs us to do [here](http://docs.vulcanjs.org/#Install))?

**Comment by mattbrunetti** [comment]
If it is possible, I'll submit a PR to VulcanJS/vulcan-docs to add instructions for that method.

If it's not possible, I'll change the title of this issue to remove the question mark.

Thanks :)

**Comment by ochicf** [comment]
Hi, I've done it as follows:

1. Download vulcan repo.
2. Delete all folders in `packages` but `_buffer` (it will say it's missing if you do).
3. Specify versions of vulcan packages you want to use, otherwise meteor will set the ones it seems fit and you will have problems. As I've seen the share the same version number, so just use `@1.7.0` (the current) for all of them.

Hope it works for you!

**Comment by defionscode** [comment]
It's practically the same thing but technically different, you could set up Vulcan as a submodule...but git submodules are PITA in my exp.
