### ISSUE TITLE
Reusable Front-end documentation/tutorials?

### ISSUE THREAD

**Issue by Kentoseth** [VulcanJS/Vulcan#1736]
On the frontpage of the site: http://www.telescopeapp.org/

The following is mentioned:

> Reusable Front-end
> 
> If you ever outgrow Nova, just keep your React components and switch in your own back-end.

Where can I find the full list of API calls to switch the backend to something else?

Also, does there exist a tutorial for using Vulcan(frontend/react) with a custom backend?

**Comment by SachaG** [comment]
There is no full list of API calls because it would depend on your own app and your own front-end. But generally, you would at least need to hook up the three main resolvers (list, single, total) and mutations (new, edit, remove) for each collection. And then of course whatever other resolver/mutations you've added.

**Comment by Kentoseth** [comment]
Thank you @SachaG 

I hope it is not too much to ask, but can you point me to an example where a custom-backend is using just 1 (or all 3 main) resolvers and 1 (or all 3 main) mutations?

If not, can you provide a small Gist showing an API (I am guessing a REST API) consuming just 1 resolver and 1 mutation? 

This would really be appreciated and I will do my best to share a full-spec example (once I understand exactly how an example-API might consume the data).

**Comment by SachaG** [comment]
Well, Vulcan is a full-stack framework so although it's possible to not use the Vulcan back-end, it's not really supported/documented, sorry.
