### ISSUE TITLE
Fragment registered, but not initialized

### ISSUE THREAD

**Issue by mzastue** [VulcanJS/Vulcan#1760]
Hi I am pretty new at Vulcan JS and moving through with Movies Example. When I try to export my component I got error as in title 
 > Fragment BooksItemFragment  registered but not initialized

Here is sample of code:
**List.jsx**
```import React, { PropTypes, Component } from 'react';
import { Components, withList, withCurrentUser, Loading, registerComponent } from 'meteor/vulcan:core';
import BooksCollection from '../../modules/Books/collection';
import BooksItem from './Item';

const BooksList = ({results = [], currentUser, loading, loadMore, count, totalCount}) =>

  <div>
    { results.map(book => <BooksItem key={book._id} book={book} currentUser={currentUser} />) }
  </div>;

const options = {
  collection: BooksCollection,
  fragmentName: 'BooksItemFragment',
  limit: 5
}

export default withList(options)(withCurrentUser(BooksList));
```

**Fragment.js**

```
import { registerFragment } from 'meteor/vulcan:core';

registerFragment(`
  fragment BooksItemFragment on Book {
    _id
    createdAt
    userId
    user {
      displayName
    }
    name
    author
    year
  }
`);
```

Is there something I do wrong?
I am also not sure about being up to date with Movies example or any other comparing it with docs and code (version of Vulcan 1.8)

Thanks in advance,
Cheers

__
Mat

**Comment by valgalin** [comment]
Hi Mat,

Please clone again the Vulcan repo. The movies example has been updated.

**Comment by mzastue** [comment]
Thanks for response. I've got the newest version of VulcanJs I guess, because I have nothing to pull from master currently. Also I've got this updated movies-example in packages and yeah it's the same as you provided above. The problem is when I am using this code (updated) I was receiving the problem in console warning log with props.
```
Warning: Unknown props `location`, `params`, `route`, `router`, `routeParams`, `routes` on <BooksList> tag. Remove these props from the element. For details, see
```

What about that?

**Comment by mzastue** [comment]
Okay, in routes there is also replaced `component` to `componentName`. And now its unable to pass imported component, because its important to pass name of registered component. That's why i receiving the above error I guess.

**Comment by valgalin** [comment]
I'd recommend that you copy the `example-movies` package, and rename your copy to like `example-books`. And then on your copy, go over to each file in the package and replace every name of movie or movies to book or books.

In this process, I hope you'll get to learn how the package works, and it's easier than following the docs, which are not yet updated. Or if you just want to have your books package, this would be the fastest way, in my opinion.

**Comment by mzastue** [comment]
Currently I got the way of thinking how packages works and what they are for. I just don't think its the best way to learn this way you recommend, because what if I will change a little bit my package and check how it works in different way. It just stop working and the warning doesn't provide any specific errors. It's just hard to understand with first meet.

**Comment by lunchboxer** [comment]
I've gotten a similar Fragment registered by not initialized error by following the example-movies tutorial to the first call of 'meteor' after 'meteor add my-package'. The problem is easy to fix, by just copying directly from the example-movies package as you suggest above.

Here's what the error shows me. The tutorial has my-package/package.js include:
`api.use(["vulcan:core", "vulcan:forms", "vulcan:accounts"]);`
while example-movies/package.js has:
`api.use(["vulcan:core@1.8.1", "vulcan:forms@1.8.1", "vulcan:accounts@1.8.1"]);`
The perceptive reader should be able to guess how this causes the error. When I run meteor add my-package I notice the following output: 
`Changes to your project's package version selections:
                                              
my-package       added, version 0.0.0         
reactive-dict    added, version 1.2.0
session          added, version 1.1.7
vulcan:accounts  added, version 1.3.2
vulcan:forms     added, version 1.3.2`

I'm not posting this for the sake of completeness. Other vulcan packages are installed at version 1.8.2, is this a bug?

**Comment by SachaG** [comment]
As far as I can tell it's a bug/inconsistency in how Meteor handles package versions: https://github.com/meteor/meteor/issues/9502

I've now started specifying package versions to avoid this.

**Comment by MHerszak** [comment]
Can this be closed, too?
