### ISSUE TITLE
How to implement Optimistic UI - Latency compensation ?

### ISSUE THREAD

**Issue by PolGuixe** [VulcanJS/Vulcan#1763]
Is there a way to systematically implement Optimistic UI in Vulcan? Apollo-React suggests this way: http://dev.apollodata.com/react/optimistic-ui.html#optimistic-basics

As I have experienced, right now, Vulcan tries to re-fetch the query that is affected by a mutation, however it does not updates the store with the new or modified data.

**Comment by SachaG** [comment]
Currently there is only the standard react-apollo way.

> Vulcan tries to re-fetch the query that is affected by a mutation

That shouldn't happen since `withList` includes a reducer that updates its results without having to refetch the query. Meaning that the query will be updated by the mutation's return value. But yes, it's not optimistic (I personally think opt. UI can be a bit of an anti-pattern once you start dealing with complex operation whose validation can fail on the server).
