### ISSUE TITLE
Extend modifier options for editMutation

### ISSUE THREAD

**Issue by MHerszak** [VulcanJS/Vulcan#1898]
Is there a reason as to why Vulcan is using set and unset only for its editMutaion? I am starting to extend on set and unset.
```
const updateModifier = (props) => ({
  $set: props.set,
  $addToSet: props.addToSet,
  $unset: props.unset,
  $pull: props.pull,
  $pullAll: props.pullAll,
  ...
});

const modifier = updateModifier(rest);

Object.keys(modifier).forEach((key) => {
  if (isEmpty(modifier[key])) {
    delete modifier[key];
  }
});
```
The reason, switching back and forth between mutation and "pure" Mongo functions on the server seems inconsistent. Also, I need to implement the callbacks by hand which seems not intuitive to me. However, maybe there is a reason?

**Comment by SachaG** [comment]
That's mainly because I didn't want Vulcan to be tied into Mongo anymore than it already was. Eventually we'll probably even drop the `set` and `unset` distinction and just assume that any `null` field on `set` should be deleted. If you need different features, the idea is you wouldn't use the default mutations and mutators anymore. 

See also #1894

Let me know if that makes sense.
