### ISSUE TITLE
Can't sort according to a resolved field

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#1908]
Hi,
I am trying to sort a collection according to a resolved field. An example use case would be to sort Posts according to the comment recency. You would have smth like: 
```js
{
    fieldName: 'lastCommentedAt',
    fieldSchema: {
        type: Date,
        optional: true,
        viewableBy:['guests'],
        resolveAs: {
            type: 'Date',
            resolver(post, args, context) {
                const lastComment = context.Comments.find(
                    { postId: post._id },
                    {
                        fields: { 'createdAt': 1 },
                        sort: { createdAt: -1},
                        limit: 1
                    }
                ).fetch()
                if (!lastComment.length) return post.createdAt
                return lastComment[0].createdAt
            }
        }
    },
```
Then I never managed to sort the `Post` collection according to the `lastCommentedAt` field either using a view or terms passed to a `withList`.
This might be a mistake from my side and not a Vulcan limitation, but I prefer to open this issue. Note: this is an example, I did not actually used the `Post` collection, so sorry I have no available repro code yet.

It behaves as if the `lastCommentedAt` field was not yet set during the sort, is it normal for resolved fields ? In this case, what would be the preferred way to implement this ?

**Comment by SachaG** [comment]
Sorts are done at the database level, and `lastCommentedAt` doesn't exist in your database, so you can't sort by it. You'd have to denormalize the field instead of using a resolver, i.e. store it "physically" in the db. 

That being said it's probably a good idea here anyway, because otherwise you'll be doing a `find` call on `Comments` every time someone loads a post. If you have a list of 10 posts, that means 10 extra db calls just for displaying those timestamps.

**Comment by SachaG** [comment]
I added a section to the docs to address this: http://docs.vulcanjs.org/field-resolvers.html#Field-Resolvers-vs-Denormalization

**Comment by eric-burel** [comment]
Ok so this matches what I guessed.  I close the issue since this is now documented, thanks a lot for this quick answer!
