### ISSUE TITLE
New users are created with isAdmin set to an empty object

### ISSUE THREAD

**Issue by ErikDakoda** [VulcanJS/Vulcan#1917]
Reproducible in the current devel branch: new users who sign up have their `users` record’s `isAdmin` field set to an empty object. An empty object is not falsy so Users.isAdmin() returns true. Here is a sample `users` record:
``` javascript
{ 
    "_id" : "FuxbyqhsRxvTzkJSB", 
    "createdAt" : ISODate("2018-02-28T01:52:37.406+0000"), 
    "services" : {
        "password" : {
            "bcrypt" : "********"
        }, 
        "resume" : {
            "loginTokens" : [
                {
                    "when" : ISODate("2018-02-28T01:52:37.411+0000"), 
                    "hashedToken" : "********"
                }
            ]
        }
    }, 
    "username" : "adminTest2", 
    "emails" : [
        {
            "address" : "adminTest2@test.com", 
            "verified" : false
        }
    ], 
    "email" : "adminTest2@test.com", 
    "isAdmin" : {

    }, 
    "displayName" : "adminTest2", 
    "emailHash" : "90bfef59093206bf3f45dfef1a7af64b", 
    "slug" : "admintest2"
}
```
Sacha said: "it might be due to adding `await` or maybe the code that makes new users admins should be in a callback instead of the `onInsert` so that the behavior can be disabled"

**Comment by Apollinaire** [comment]
On the master branch (v1.8.9) isAdmin is not set at all, looks like the onInsert works in a weird way, because it does set isAdmin to true for the first user, but it's not set to false for the next users, just not set at all. 
Can be reproduced in example-simple: sign up a first user, which will be admin and have isAdmin=true, then all the other accounts you sign up with just don't have the field registerd in mongo, and when queried isAdmin returns null. 
Weird behavior from onInsert here.

**Comment by SachaG** [comment]
Looks like `onCreateUser` doesn't work well with `async/await`. I'll fix it for now but we might need to come back to this later. 

https://docs.meteor.com/api/accounts-multi.html#AccountsServer-onCreateUser
