### ISSUE TITLE
Cannot integrate Semantic-UI with Vulcan

### ISSUE THREAD

**Issue by ghost** [VulcanJS/Vulcan#1935]
Hi,

Because Vulcan uses Meteor it has problems showing icons imported from `semantic-ui-react` and `semantic-ui-css` library even though it was installed through `npm`
As it is described in the [installation instructions](https://github.com/Semantic-Org/Semantic-UI-Meteor#meteor-13-1) you need to remove `standard-minifier-css` and add `semantic:ui`, `juliancwirko:postcss`, `less` and `jquery`.

But Vulcan seems to use the `standard-minifier-css` package and it cannot support two minifier packages: `standard-minifier-css` and `juliancwirko:postcss`.

Does anybody know a workaround?

**Comment by SachaG** [comment]
If you use the 2-repo install you can modify the core to use the other minifier package. Not a great solution but it should work?

**Comment by gabimoncha** [comment]
I will try, but I don't think it is a great idea. Isn't `standard-minifier-css` used in the build script?

**Comment by gabimoncha** [comment]
Hi, @SachaG ,

I didn't have time to check it works yet, but I got [this response](https://github.com/Semantic-Org/Semantic-UI-React/issues/2662#issuecomment-374253419) from the  `semantic-ui-react` repository team.

They say that the build process is not including the font files.

If this is correct, I need to know if `standard-minifier-css` is used in the build script and if it will be needed for a larger period of time, in order to know if this package should get this much attention.

**Comment by SachaG** [comment]
@ErikDakoda do you know anything about this?

**Comment by ErikDakoda** [comment]
Material UI uses JSS, which compiles JS to CSS at runtime, so it does not have this problem.

**Comment by nolandg** [comment]
Semantic UI is working great for me with no changes to core. But I'm not using any UI elements from Vulcan. I made a package to replace them all with SUI versions.

**Comment by SachaG** [comment]
@nolandg is that package public? I'd love to start thinking about how to decouple Vulcan from bootstrap.

**Comment by horodnicdragos** [comment]
@nolandg 
It would be really helpful if we could see the changes that you've made to get this working. I also agree that Semantic offers the most intuitive and minimalistic approach to the referenced issue above. 

@SachaG 
Making Vulcan UI library agnostic sounds like a great idea. If there's any way I can help it would be nice to have the issue split in smaller tasks and see where I can fit in.

**Comment by SachaG** [comment]
@horodnicdragos you can check out the thread linked above for more info on that.

**Comment by nolandg** [comment]
@horodnicdragos 
https://github.com/nolandg/vulcan-semantic-ui
I've thrown my semantic ui + vulcan repo on github. It's very rough and dirty at the moment because this is my first experiment with Vulcan and this project deadline is the 14th. My intention is to clean it up and make usable for others in the near future but not now. I hope you can make some sense of it. Currently it just replaces the Vulcan ui components with SUI ones and makes a nice login form that displays all the login errors etc.

The other big thing it does is makes some middle ground between totally DIY forms/document editing and using Sacha's autoform. I don't like any sort of autoformy things because I want total fine grain control over building each form, I have few use cases for canned forms. So I wrapped SUI components with my own. See FormField.jsx. I also added RichText (based on React Draft) and LocationAutocomplete (based on Google Maps API) components. These wrappers play nice with my EditForm component that handles all the state changes, validation, and and displays field-level error messages. So you basically create your own form, piece by piece in a component that extends EditComponent. You have to do more work than using Autoform but less than totally manually. This is the first iteration and I can be simplified a lot.

Example of using my EditForm component:
````
class ElectricityActivityRecordEditForm extends EditForm {
  constructor(props) {
    // Tell the parent component which fields we're trying to update
    const fields = ['activity', 'startDate', 'endDate', 'data'];
    super(props, fields);
    
    // Set default/initial values for some fields. 
    // EditForm will populate the rest from the either the document in db or the schema
    _.set(this.state, 'values.activity', 'electricity');
    _.set(this.state, 'values.data.units', 'kWh');
  }

  render(){
    const { FormField, DateRangeField } = Components;
    const { values, errors } = this.state;
    const fieldProps = { values, errors, onChange: this.handleChange };
    const { inventory } = this.props;
    const initialMonth = inventory?getMidpointMoment(inventory.startDate, inventory.endDate):null;

    return (
      <Form error={!!this.state.errors}>
        {this.renderMessages()}

        <DateRangeField label="For what period is this bill for?" startName="startDate" endName="endDate" initialMonth={initialMonth} {...fieldProps} />

        <FormField label="How many kilowatt-hours are on this bill?" name="data.energy" widthEm={9} {...fieldProps} />

      </Form>
    )
  }
}

registerComponent('ElectricityActivityRecordEditForm', ElectricityActivityRecordEditForm,
  [withEdit, {collection: ActivityRecords, fragmentName: 'ActivityRecord'}],
  [withRemove, {collection: ActivityRecords}],
  [withNew, {collection: ActivityRecords, fragmentName: 'ActivityRecord'}],
  withCurrentUser
);
````

You should be able to usually see a working copy of my dev site at https://climateaction.fun/ Try registering and logging in to see errors etc (only password login right now).

Let me know if you have questions.

**Comment by SachaG** [comment]
@nolandg the forms look good! I think my next focus will be the UI stuff, it'd be great to have bootstrap/material/semantic versions of Vulcan.

**Comment by nolandg** [comment]
Thanks. Yes, I'm all for ui agnostic and can certainly help out with the sui part.

**Comment by eric-burel** [comment]
Closing, see #2189 to discuss semantic UI integration.
