### ISSUE TITLE
Step form discussion

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/Vulcan#1937]
I'm writing a stepped form and if it turns out well i will submit a PR. I'm creating this issue to be able to discuss the best way to implement this with anyone interested in it, and to get your feedback on the implementation i'm suggesting behind.

Here's how i imagine the stepped form to be written: 

Each step would be a SmartForm, and the StepForm would connect each step with callbacks. I have not tried it yet, but i think it is possible to link two steps through the successCallback and cancelCallback of the SmartForm. 

Basically all can be done just by connecting SmartForms, which is already possible because SmartForm displays a big customization api through its [props](https://github.com/VulcanJS/Vulcan/blob/7061483af8bdb04bdcc71dc8faa10e23d964c199/packages/vulcan-forms/lib/components/FormWrapper.jsx#L242). 

StepForm Props: 
- steps: [object]  where each object would have Smartform props, used to define each step. 

Feedback will be appreciated 😃 

Possible enhancement: We could also add a label per step, to be displayed in a timeline, but for this i would need someone to implement a timeline component in react-bootstrap, since i only use material-ui.

**Comment by SachaG** [comment]
I think that for something like this it's best to leave each user implement their own version, since SmartForms already does a lot of the work. You could contribute an example of how to implement this to the Starter repo though :)

**Comment by dbrrt** [comment]
@Apollinaire I think it'd be better to use a Global Store container (such as Redux) rather than relying on callbacks for each SmartForm. This way, you could isolate more efficiently your components.

**Comment by Apollinaire** [comment]
@dbrrt thanks for the suggestion. I never used redux, which is why i did not think about it in the first place. 
I'm not sure it would be applicable here, because i want to create a versatile and easily reusable component: you would only have to declare the collection, fields, documentId for each step and it would generate by itself. I'm afraid that exporting a modular state like this to a global store might be tricky to make reusability easy? I absolutely don't know anything about redux so i might be 100% wrong.

Would redux support a nested object like this maybe ? 
```
state.stepForms |
                | state.stepForms.formName | state.stepForms.formName[0] -> contains props of first step of formName
                                           | state.stepForms.formName[1]
                                           | etc..

                | state.stepForms.otherFormName | ...
                | etc...

```
What i like with callbacks is that everything is kept in the StepForm component state, so nothing goes global and nothing can interfere with another StepForm component somewhere else in the app.

Also @SachaG what do you think of this option vs callbacks?

**Comment by dbrrt** [comment]
@Apollinaire Absolutely, do you need some help to get started with it ?

**Comment by SachaG** [comment]
The callbacks would be used for going to the next step once you've submitted a form, right? I don't really see what they have to do with Redux or how you manage state?

**Comment by dbrrt** [comment]
@SachaG It can be painless to store form inputs in a global store to ease the development of each linked step. A callback would've been a good choice for a standard form, if you plan to create a form composed of several component, and result of step1 might be used in step2 and/or step3, a global state container is a most suitable solution than passing all the data in callbacks.
Also, if you want to be able to switch from step3 to step1 (assuming step1 and step2 completed), I don't see how callback can be a "more convenient" solution.

**Comment by SachaG** [comment]
I think we're mixing different concerns here. If you're using SmartForm, then all you need to do is have, say, four SmartForms labelled 1 to 4 on four different routes, and use the submission callbacks to go from one to the other. 

If you want to not use SmartForm and manage forms through Redux then that's also a valid solution, but it's a completely different thing.

**Comment by dbrrt** [comment]
@SachaG thanks for your feedback. He didn't mention synchronization with several routes, but if that the case Redux itself might not be the solution as it's a front-end library, and SmartForm won't be directly linked with the back-end.

@Apollinaire I'm currently implementing something very similar with Redux, and can help if required.

**Comment by Apollinaire** [comment]
Indeed my goal is to use one smartform for each step, so i would not be storing all the inputs in state, they would be stored in the database each time you click 'next'. 
I did not want to make different routes for each Smartform though, just to make it look seamless between each step, to make it integrable into other components (like a modal for example).
I might not have been clear in my first explaination. Basically i want to make some kind of stateful HoC around one smartform component, and update the hoc's state when the 'next' or 'previous' button is clicked, then re-render the Smartform with props from the next step. So no routes, just different states in one component.

**Comment by SachaG** [comment]
Yeah you can also do it without different routes. I just like having different routes personally because if people close their tab or browser they can resume on the same step,

**Comment by Apollinaire** [comment]
Good point @SachaG  
Actually i'm running into an issue i did not expect: it seems that when you change the collection prop from the Smartform, it does not update it on the form, even though SmartForm is re-rendered because you can see the fields change. 
I tried giving SmartForm a `key` prop (cf [reconciliation](https://reactjs.org/docs/reconciliation.html#keys) ) that would be updated when going to the next step, but i'm running into some scope errors :
```
TypeError: this.getCollection(...).simpleSchema is not a function
    at FormWrapper.getSchema (FormWrapper.jsx:62)
    at FormWrapper.getFragments (FormWrapper.jsx:77)
    at FormWrapper.getComponent (FormWrapper.jsx:149)
    at new FormWrapper (FormWrapper.jsx:53)
``` 
I'm guessing using different routes would solve this since you would have 'contained' smartforms and not one that's just being updated

**Comment by SachaG** [comment]
Maybe that's because the form is instantiated in the constructor and not the render?

https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-forms/lib/components/FormWrapper.jsx#L53

**Comment by dbrrt** [comment]
@Apollinaire Can you share some code? It'd be easier to debug this way.

**Comment by Apollinaire** [comment]
> Maybe that's because the form is instantiated in the constructor and not the render?

That must be it, i thought adding the key prop would trigger a re-construct . i'll investigate further.

@dbrrt it's part of a private repo right now but i'll make a public one with the code this weekend. 
@sacha this repo will become a plugin package instead of a vulcan-starter example

**Comment by Apollinaire** [comment]
I created a repo here: https://github.com/Apollinaire/vulcan-stepform 
StepForm.jsx is the component itself, form.jsx is how i instantiate it.

**Comment by dbrrt** [comment]
@Apollinaire Thanks for sharing it, the approach looks good (for your case), I assume that you could propose a step form wizard as a HOC, where user could have more flexibility on input, for instance passing custom fields such as file upload fields, or theming. It sounds very opinionated as you're passing directly a collection name (MongoDB) and some vulcan user might just want to use another DBMS with this component (as GraphQL supports any backend out-of-box), but as it relies on SmartForms, I suppose it's ok in this case.
Complex multi-steps forms are definitively not that easy to abstract :)

**Comment by Apollinaire** [comment]
> It sounds very opinionated as you're passing directly a collection object (MongoDB) and some vulcan user might just want to use another DBMS with this component

Well yes it's opinionated because it's a Vulcan component and not a React component, and the idea is to reuse what has already been done with SmartForm and not create a stepform from scratch (yes I'm a lazy dev). And since Vulcan only supports MongoDB for now there is no need to extend to the use of another DBMS. If things work well when Vulcan goes DB-agnostic there will be very little work to be done on this component, since most of the DB stuff happens at the level of SmartForm and the schema, and StepForm is just passing it the props you give it with some additional stuff. 

>  I assume that you could propose a step form wizard as a HOC

Could you develop on that subject?

**Comment by dbrrt** [comment]
@Apollinaire actually, doing such thing is not being lazy, it could prevent over engineering, which can be convenient if you need to deliver earlier.

` I assume that you could propose a step form wizard as a HOC

Could you develop on that subject?`

The idea wouldn't be that far from what you've already done, but rather than hardcoding the form engine (in this case `SmartForm`), in your component you could find a way to pass it as a prop to a more abstract component, so this way, if someone wants to use another form engine, it could be passed directly as a component enhancer.
I was refering to this part of the React documentation :
https://reactjs.org/docs/higher-order-components.html

Again, I'm just sharing ideas, not giving necessarily the best answer :D and your solution, even if it's more opinionated than a composable "FormEngine", might just work fine in your case. Also, SmartForm might be easier to synchronise with Vulcan routing than a "solution from scratch", if you want to have one step per route.

**Comment by Apollinaire** [comment]
I see now the difference with what i've done yes! But indeed I have to deliver soon, so i'll stick to a simple wrapper around SmartForm. 
I have updated the repo with a version that actually works! I found out the error `TypeError: this.getCollection(...).simpleSchema is not a function` came from an export that was wrong, so changing the `key` prop actually works to completely update a SmartForm. 

I think i'll look into a way to force required fields through the props of SmartForm. Any ideas @SachaG ?

**Comment by dbrrt** [comment]
@Apollinaire I think that you can already describe that in your SimpleSchema, but I'm not sure that it'll be propagated to SmartForm.

**Comment by Apollinaire** [comment]
Yes you can already do it within SimpleSchema and SmartForm but i find it unpractical, mostly because it acts at a document level and not at a form level. This makes splitting into steps difficult, because it forces you to have all the required fields at the creation of a document. 
For example, say I have a three-step form, and step 2 & 3 use the same collection and same document. Well using what I've done with Stepform wouldn't allow you to have any required fields in step 3 because you would have an error validation at step 2 for these fields. 

I just saw what was made by Sacha on the `devel` branch, about the rework of SmartForm, and i think that now, thanks to the [new createfield function](https://github.com/VulcanJS/Vulcan/blob/ceabbc13148274a72e7daf26756a726e23168e66/packages/vulcan-forms/lib/components/Form.jsx#L241) maybe i could make Smartform use a different schema than the one used to create the collection, this way it would solve the problem i exposed just above, because you could separate the collection from the validation rules. This would also make possible having a form with required fields on a user document, which is not supported at the moment.

**Comment by dbrrt** [comment]
@Apollinaire if you're really in a rush, you can also consider creating custom mutations for each step, waiting for the new features of SmartForm, using your own components based on your SimpleSchema definition ?

**Comment by SachaG** [comment]
> Stepform wouldn't allow you to have any required fields in step 3 because you would have an error validation at step 2 for these fields.

I see what you mean. The problem here is that `optional` on the schema acts at the database validation level. So we would need another property that acts at the form level. I actually ran into that same issue for a user profile form recently: I wanted to make the "address" field required to complete the form, but not required for the actual user object (otherwise you wouldn't be able to sign up at all without completing that field first). 

In the end I'm just showing a different success message in `successCallback` based on whether the profile is complete or not. 

I'm not sure what the best API would be. Probably just creating a new property altogether to avoid conflicts with `optional`'s current behavior?

**Comment by Apollinaire** [comment]
Haha i ran into the 'required field in the Users collection' problem earlier too!
@SachaG So the address field is `optional = true` in the schema you use to create the collection, but you check that it's not empty in the successCallback? If we create a function that analyses a SimpleSchema object and compares it to the user entries that would make it for custom validation? 

What bothers me with this solution is that it might be a security breach, because this callback is client-side ( i assume) so someone could just change it and pass empty values for required fields (required by the form custom schema and not by the collection schema ).

About the API, I don't have an idea of how to make this work. And it would mean that we are stepping a little further away from the original SimpleSchema API

@dbrrt I'm not that much in a rush, and i know that for my next delivery (releasing May 14th !) I can always make my form by hand if i need  it. I just want to make something reusable, because next year i'll have to do the same, and the year after, and maybe several times a year haha. 
Your suggestion gave me an idea: The form builder could create its own mutations & mutators based on the custom schema and the collection you give it, and wrap its children with HOCs like withEdit or withNew, but the mutations with these custom HOCs would be the ones created before. That could work i think

**Comment by SachaG** [comment]
Well you will never be able to prevent people from *not* submitting a field. It's up to you to make sure your server logic deals with partial documents accordingly. 

I think the best API would probably be something like a `requiredFields` prop on the SmartForm component. It's pretty self-explanatory that way. The only issue is that this would require adding a client-side validation step, which we currently don't have…

**Comment by Apollinaire** [comment]
Ah i thought you were talking about a property to put in the schema. Yes setting some required fields would work if you add a clientside validation layer in SmartForm, and make it cancel the submission to the server if the entry is invalidated

**Comment by eric-burel** [comment]
Would something like adding a "draftable" boolean on schemas be feasible? Managing draft, e.g storing an item only half filled because you are only on step 2 of the form, is always a tough question, not only with Vulcan. There is a big difference between validation requirements for a draft object and a final object, while the schema is essentially the same.
Right now I guess I would either need to modify the schema to remove all validation requirements (bad and intrusive),  creating a second draft version of the collection (why not but it quickly makes things more complicated), or creating as many collections as steps in the form (same, why not but heavy and then need to build the whole object on success).
By allowing a draft mode, you could skip all "required" fields validation until the final validation. When the object is eventually complete, the "draft" tag could be removed from the object.
By default all draft objects could be ignored by requests, except if you explicitly allow them because you are writing a stepped or long form.

Anyway thanks @Apollinaire for raising this issue and creating a package, I ran into this issue in my last project and wondered how to build such a form and had no clue before your work (I eventually delivered the app without stepped forms).

**Comment by SachaG** [comment]
I think draft mode is a different issue, but it's already possible currently. The way I'd do it is have an `status` field that defaults to `draft`, and then every time the document is modified check if fields `foo`, `bar`, and `baz` are present. If so, change the `status` to `published`.

**Comment by eric-burel** [comment]
I think of draft because you may need a draft saving pattern if you implement a "Save & continue" button between steps. This applies to any kind of long form (best example is taxes), there are different patterns, mostly by using multiple collection or a specific draft collection, or using one collection but loosening the validation requirements
I wonder the feasibility of a one collection pattern (no additional draft collection) _without_ the need to modify the requirements at the field level.  It would even allow partial document validation, so that we can check the existing field requirements but ignore empty fields temporarily.
E.g your income is mandatory in a taxes form (`optional: false` in the schema) but you would still accept it to be empty if its a draft (e.g because your user is only at step 2 and income appears at step 3). If it is filled, we can still check if it is a positive number, even if the rest of the document is still not filled.

So your solution is to write a custom edit mutation and check if non-optional fields are filled or not in it ? Can you still use the simple-schema validation and tell it not to check? There seems to be a `ignore` in simple-schema option that could allow this behaviour but I wonder how I could set it to true in Vulcan.
