### ISSUE TITLE
Callback hooks issue with async/await

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#1949]
Currently a `collection.before.sync` callback gets called like this in `mutator.js`:

```
modifier = await runCallbacks(`${collectionName}.edit.before`, modifier, document, ...);
```

So any async/await code inside a callback hook is resolved at the mutator level.

The issue is that if two hooks both have async/await code, since the promise only resolves at the mutator level, it won't resolve *in between* hooks. Meaning that the second hook will receive a Promise as its `modifier` argument instead of a normal object.

The solution would be to `async/await` inside `callbacks.js`, where `runCallbacks` is defined. But the problem is that `runCallbacks` is used in many places where it *can't* (or shouldn't) be async, and handling async properly in all those places would be a big refactoring. 

For now an easy enough workaround is to only use a single async callback on each hook, but it's not a great long-term solution.

**Comment by SachaG** [comment]
> I'm guessing the runs property is actually indicating if the callback is being called with runCallbacks or runCallbacksAsync. If this is the case, I think right with this new runCallbacks behavior is misleading: there are hooks being called with await, hence accept async callbacks, that are marked with runs: 'sync' (examples: new.before, new.sync, new.after, edit.before, edit.sync, edit.after).

Yep, that's right. 

> should runCallbacksAsync be renamed to avoid confusion? I think it should, since what it essentially does is to run callbacks in parallel.

We could rename it while keeping `runCallbacksAsync` available as an alias for backwards compatibility?

> should runCallbacksAsync still be only valid on the server? I guess this decision was taken because the use of Meteor.defer, but now with Promise.all it can also be used in the client

I haven't really run into use cases where I'd need it on the client but if it makes the API easier to understand why not. I'm not against it.

**Comment by SachaG** [comment]
Oh btw the `runs: async/sync` thing was just for the docs originally, and it does correspond to `runCallbacks` vs `runCallbacksAsync`. I don't mind repurposing it for your usage but it might be better to use a new flag altogether? Since we're now talking about two types of "sync" callbacks. 

Maybe `type: sync/async/parallel`? What naming would you suggest?

**Comment by SachaG** [comment]
Thinking about it some more I'm not sure having a `runs` or `type` property is that useful… I guess it could help detect when people are using `await` with a callback that doesn't support it? 

What if instead you had three `runCallbacks`, `runCallbacksSync`, and `runCallbacksParallel` function? or maybe `runCallbacks({mode: 'sync/async/mixed/parallel})`…?

**Comment by ochicf** [comment]
Hi @SachaG 

>We could rename it while keeping runCallbacksAsync available as an alias for backwards compatibility?

Of course, and it would also be good to warn with a deprecation message so other packages can be updated until the alias is removed.

>I haven't really run into use cases where I'd need it on the client but if it makes the API easier to understand why not. I'm not against it.

I haven't neither, but I've found myself using `runCallbacks` in custom packages quite often, so maybe someone has the same need with `runCallbacksAsync`.

---------------

About the naming/how to determine the allowed callbacks, I don't have any proposal I'm super sure of, but I think maybe we are mixing concepts and use cases. If we think about consumers of this run callback system, we have:

#### Point of view of the runner of the hook

When running a hook, the runner is defining how the hook should work and what callbacks should be allowed. The runner has this possibilities:
  1. run callbacks in series (calling reducers) or in parallel (or better said, [concurrently](https://softwareengineering.stackexchange.com/questions/190719/the-difference-between-concurrent-and-parallel-execution)). This choice depends on what the hook is supposed to do (or better said, whan the runner expects the user to do). Usually `runCallbacks` is used to alter a value and `runCallbacksAsync` to perform side effects from a given value
  2. await for a value or not. This is limited by the context where the hook is run. If the context is sync -and has to be mantained that way-, the hook will exclusively allow sync callbacks.

All of this will define how the hook should be registered so its callback execution (and return value) is handled correctly.

#### Point of view of consumer adding a callback to a hook

By adding a callback the same two variables must be known in order to write the callback accordingly, but this depends on the hook being added the callback to:
  1. when adding a callback to a hook that is run in serie, callbacks act like reducer and should return a new value (if they don't, the old is used). For parallel hooks, they act as any callback and can return a value or not
  2. adding sync or async callbacks will depend on the defined sync/async context of the hook.

#### Conclusions

1. a hook being run in series or parallel doesn't make a big difference for a consumer when adding callbacks (in terms of signature; of course result will vary), but indeed a consumer needs to know how the callbacks are being run, so we might want to register that, so maybe the `runs` property could be used for this, being the allowed values the different types of execution we have (for `runCallbacks` might be `runs: 'consecutive'`; for `runCallbacksAsync` could be `runs: 'concurrent'`)
2. a hook's sync or async context is a bigger problem, since added callbacks could break the runner's code by returning a promise instead of a value, and this is why they should be checked in order to discard them in case they do not match the expect context. To determine this, a flag could be used when registering the hook being `sync: true` to allow only sync callbacks

---------------

Sorry for the wall of text. In my opinion this hook system is super useful I find myself using a lot to allow other packages to inject logic at certain points, so I'm really interested to improve it.

Also sometimes I think amb not explaining myself clear enough, so please let me know if that is the case.

**Comment by SachaG** [comment]
I think your explanations are great, it's just a lot of abstract concepts to wrap your head around :)

A few thoughts:

1. Currently calling `registerCallback` is optional, it's only used for documentation purposes. So I don't know if we can rely on it too much. I also don't like mixing documentation and logic (i.e. making `runs` actually affect the behavior of your code).

2. I agree that the tricky issue here is when a hook returns a Promise when you expect an object (I've had this happen a couple times where I couldn't figure out why `foo.bar` was `undefined` before realizing `foo` had become the Promise instead of the previous callback's return value). 

3. We could also think about just changing the callback API altogether. Maybe from

```
runCallbacks(name, arg1, arg2, ...);
```

To:

```
runCallbacks(name, iterator, arguments, options);
```

Or even more explicit:

```
runCallbacks({ name, iterator, arguments, options });
```

This would give us more flexibility to specify options, etc. 

So my overall conclusion is that for now we should keep the first PR simple and backwards-compatible, even if this means not addressing the "async function in sync context" issue for now. And later on, we can migrate to a new, cleaner API. What do you think?

**Comment by ochicf** [comment]
I think you are completely right in everything. I've been thinking about the `registerCallback` and, besides of being optional, it makes the `runCallbacks` function to be less pure and maybe it'd introduce some issues aswell.

I'm reverting the commits so the PR is kept simple: only the await between callbacks feature will be will remain.
