### ISSUE TITLE
Apollo 2 Migration

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2081]
I'm opening a new thread to track my progress on [the migration to Apollo 2.0](https://github.com/VulcanJS/Vulcan/tree/apollo2) ([starter repo](https://github.com/VulcanJS/Vulcan-Starter/tree/apollo2)). 

## Main Tasks

- [ ] Apollo Client 2
  - [x] Post-mutation data updates
  - [x] Replace Redux with link-state
- [ ] Apollo Server 2
- [ ] React Router 4
  - [x] Generate routes
  - [ ] Add callbacks, options, etc.
- [ ] SSR

**Comment by SachaG** [comment]
Related: 

- https://github.com/apollographql/meteor-starter-kit/issues/54
- https://github.com/szomolanyi/MeteorApolloStarter

**Comment by SachaG** [comment]
Here's a round-up of the relevant code that will need to be migrated/refactored/discarded: 

### `vulcan:lib` client

- `auth.js`: https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/client/auth.js probably not needed anymore
- `inject_data.js`: https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/client/inject_data.js reconsider if still needed
- `render_context.js`: https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/client/render_context.js port to Apollo Client 2 if still needed

### `vulcan:lib` modules

- `apollo.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/modules/apollo.js port to Apollo 2 (see `client/apollo2.js`)
- `redux.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/modules/redux.js replace with apollo-link-state

### `vulcan:lib` server

- `apollo_server.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/server/apollo_server.js port to Apollo Server 2
- `inject_data.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/server/inject_data.js reconsider if needed
- `meteor_patch.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/server/meteor_patch.js reconsider if needed
- `render_context.js` https://github.com/VulcanJS/Vulcan/blob/apollo2/packages/vulcan-lib/lib/server/render_context.js migrate to Apollo Server 2

### `vulcan:routing`

See contents of https://github.com/VulcanJS/Vulcan/tree/devel/packages/vulcan-routing/lib Currently moved to `vulcan:core/client/start.jsx`.

**Comment by SachaG** [comment]
> Using Meteor forces us to keep using apollo-sever-express, though we don't need to explicitely create an app. There are currently no example of a Meteor integration with a standalone Apollo server (so without express, using only the builtin HTTP server).

Maybe someone from the Meteor/Apollo team could help us? Or maybe @lorensr would know?

**Comment by lorensr** [comment]
Don't know! I had this question as well: https://github.com/apollographql/apollo-client/pull/3739#issue-203997257

**Comment by lorensr** [comment]
@benjamn Is there a better way to set up Apollo Server inside Meteor? We're currently recommending https://www.apollographql.com/docs/react/recipes/meteor.html#Server

**Comment by eric-burel** [comment]
Hi, 

Actually I think I figured this out wrong in the first place. It's not `apollo-server-express` that spawns the Express instance, it's just a connector. You always have to pass it. 
`meteor/webapp` does however setup a full fledged server (with connect to be precise, I guess this is mostly the same thing as Express? Not familiar with Node subtleties), with cookies, compression, etc., and your custom handlers. 
So `apolloServer.applyMiddleware({ app: Meteor.connectHandlers })` is roughly equivalent to `apolloServer.applyMiddleware({app: yourExpressServer })`.

So the question itself does not make sense, you can't use the Apollo builtin server, at least not using the `meteor/webapp` package, because it's implementation rely on Express already. Anyway in Vulcan case it's a better idea to rely on Express due to 3rd party plugins compatibility (see graphql-voyager integration tested by @Apollinaire).

I'll check that and try to add a custom middleware in a few hours and let you know.

**Comment by eric-burel** [comment]
Closing in favor to https://github.com/VulcanJS/Vulcan/issues/2171
