### ISSUE TITLE
Vulcan Book - UI Debug

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2203]
I've added a small UI to visualize core components more easily on branch [`feature/vulcan-book`](https://github.com/VulcanJS/Vulcan/tree/feature/vulcan-book). It is meant to help the development of additional UI libs (see  #2189, #2190, #2191).

I've defined a callback to register stories:
```
addCallback('stories.register', (stories) => (
 [
    ...stories, // other registered stories
    {
      group:'MyComponent',
      name:'My Component Without data',
      render: () => <MyComponent data={[]} />
    }
 ]
))
```
![image](https://user-images.githubusercontent.com/7983005/52868779-832fdd00-3144-11e9-8634-79df5c050591.png)

I have a few questions:
- First, what do you think of this implementation ?
- Is there a way to load/run code only in debug mode? If you want to register stories from another package, it's technically doable but the problem is that the stories will have to be part of the actual code (which is a reason why storybook has its own build system).
- Do you think that creating an additional "registerStories" function is worth it ? It would be based on this `stories.register` callback, which I find a bit tedious to use. It would only make sense if we register stories from other packages though.

So far I've written only 2 stories to test the UI.

 I've loaded a full Datatable, but it's not a very good idea because there are too many side effects (you need to be logged in to see action buttons for example). For the moment I think it should be limited to purely visual components (eg DatatableHeader, layout components, form inputs, etc.).

**Comment by Apollinaire** [comment]
> Is there a way to load/run code only in debug mode?

Two ways from what I know: 
- work in a `debugOnly` package
- use dynamicLoading from a normal package: 

```js
if (Meteor.isDevelopment){
  import(./myStory);
}
```

With the second way, the stories will always be built, even for production builds, but they will never be loaded, either on the client or the server.

**Comment by SachaG** [comment]
Very cool! But as a more general question, do you think it's better to invest time in this direction rather than work out how to use Storybook with Vulcan? Or do we just think it's impossible? Or is it worth it having our own component explorer anyway since we can do thing Storybook maybe can't? (show logged in/logged out versions, etc.?)

**Comment by eric-burel** [comment]
The problem with Storybook is that integrating to Meteor it seems very difficult. If no solution is found within a few weeks/months I may try to help on this, but I think that right now Storybook itself is undergoing some refactor so it may not be worth it. With Storybook however you should be able to implement any behavior you want, it's really powerful when combined to mocks and other testing tools, so I think it would not be useful to have our own solution.

In the short run I just wanted to be able to visually debug all the core components, before starting to merge Material UI. The version I pushed yesterday is already ok for this.

However since the API is quite simple and I already developed an UI, I thought maybe we could make this public, as a very limited but working palliative to Storybook. It can be quick to implement if we are smart about it. But the problem is that currently that means including the stories in the actual code :/ 

Using dynamic loading could be an interesting solution. I could detect all files named "stories" or "story" and load them automatically. The most difficult part is that Meteor behaves very weirdly with paths, I did not manage to get a correct `__dirname` value yesterday. Also it would make bundle bigger. So I am not sure if we should encourage this pattern.

Anyway I will focus in adding stories for all core components first, those are just ideas.

@SachaG what do you think about the use of callbacks? Sometimes I feel like we miss a middleman between `registerSetting`, which is very static and tied to `settings.json`, and `callbacks`, which are sometimes a bit tedious to use since they always must be functions that runs in chain. Maybe an API like `registerArray('stories'); addArray('stories', [ /* your stories */]);`?

**Comment by SachaG** [comment]
That makes sense.

> The problem with Storybook is that integrating to Meteor it seems very difficult.

But what if we focused on integrating it with Vulcan, not with Meteor? What I mean is that Vulcan components don't depend on any Meteor feature. So maybe it'd be possible to somehow tell Storybook how to understand `meteor/vulcan:core` even if it doesn't know what "meteor" is? Even if that means only supporting a subset of Vulcan core features within Storybook maybe?

> @SachaG what do you think about the use of callbacks? Sometimes I feel like we miss a middleman between `registerSetting`, which is very static and tied to `settings.json`, and `callbacks`, which are sometimes a bit tedious to use since they always must be functions that runs in chain.

What I like about something like `registerSetting` is that it's very explicit, and also can have an API tailor-made for the use case. If you need something like `registerArray` I don't mind adding it, but personally I think for more common APIs it's good to have a dedicated function. Also makes searching through the codebase easier and understanding the code more manageable (for example I find the callback code pretty hard to understand since it has to do a lot of things).
