### ISSUE TITLE
Error: cache.readData is not a function

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2207]
Running into this: 

```
modules.js?hash=22876848e9c5f09c553595aa535504fb41f80976:46649 Uncaught (in promise) Error: Network error: cache.readData is not a function
```

I think the code that's triggering it is: 

```
flash({
  id: 'users.edit_success',
  properties: { name: Users.getDisplayName(user) },
  type: 'success',
});
```

**Comment by SachaG** [comment]
I wonder if maybe we should consider reimplementing flash messages with the Context API? It might turn out to be simpler?

**Comment by SachaG** [comment]
It seems like maybe it should be `readQuery` instead of `readData`? And also `    const currentFlashMessages = cache.readQuery({ query: getMessagesQuery }).flashMessages;` instead of `    const currentFlashMessages = cache.readQuery({ query: getMessagesQuery });`

Even after fixing these issues and setting `__typename: 'JSON'` on the returned `flashMessage` I still get another error:

```
Missing selection set for object of type JSON returned for query field flashMessages
```

**Comment by eric-burel** [comment]
I used this component as a showcase for apollo-link-state in replacement to redux, it could totally make sense to replace it totally with context. 
There also are big chances that the current implementation is wrong, since I use Vulcan I actually never written graphql queries and mutations, this component is my first one. That would be good to have a unit test for this component too.

**Comment by SachaG** [comment]
OK, let's try to fix it with Apollo Link first anyway. I might as well learn how the cache works.

**Comment by eric-burel** [comment]
Closing as stale I think
