### ISSUE TITLE
Folder disappear in storybook

### ISSUE THREAD

**Issue by juliensl** [VulcanJS/Vulcan#2409]
Hi !

In storybook, the folder with the inputs of forms does not appear at the first launch of storybook.
I need to rebuild the webpack (I guess it is what happen) to see it : 

![bug_storybook](https://user-images.githubusercontent.com/43228020/67000492-37b93e80-f0d8-11e9-9f16-049695a45621.gif)

I think it is a synchronous problem, but I do not know how to fix it x)

Does anybody have an idea ? :)

**Comment by eric-burel** [comment]
Fixed  the error is calling `Components[name]` outside of a React render function. At this point the `Components` object is not populated.  But on reload it appears again because then `Components` is populated. I fixed this by rewriting the function a bit so it calls Components[name] later, when it's populated.

See https://github.com/VulcanJS/Vulcan/issues/2406
