### ISSUE TITLE
Handle double nesting in blackboxed array

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2524]
```
//articleschema
articles: {
      type: Array,
      blackbox: true,
      // typeName:'articles',
      canRead: ['guests'],
      group: articleGroup,
      optional: true,
      // canCreate: ['members'],
      // canUpdate: ['members'],
    },
    'articles.$': {
      type: articleSchema,
      // blackbox: true,
      // typeName:'articles'
    }  ...
```
```
const schema = {...  
//blocks
blocks: {
    type: Array,
    canRead: ['guests'],
    group: blockGroup,
    optional: true,
    canCreate: ['members'],
    canUpdate: ['members'],
    blackbox: true
  },
  'blocks.$': {
    type: blockSchema,
  }...
```
Error
```
Error: Unknown type "LetterBlocksArticles". Did you mean "LetterBlocksSortInput", "LetterBlocks", "LetterBlocksFilterInput", "LetterSortInput", or "CreateLetterBlocksDataInput"?
```

I don't know yet if the solution is to add `blackbox:true` to the `blocks.$` too, but anyway this should either display a relevant warning or not throw an error. Maybe `isBlackbox` check should be improved to test if array parent is blackboxed

**Comment by GraemeFulton** [comment]
When `blackbox:true` is added to `blocks.$`, I get this error:

` Error: Unknown type "CreateJSONDataInput". Did you mean "CreateUserDataInput", "CreateBlockDataInput", "UpdateUserDataInput", "CreateLetterDataInput", or "CreateUserInput"?
W20200217-12:33:30.481(0)? (STDERR)
W20200217-12:33:30.482(0)? (STDERR) Unknown type "UpdateJSONDataInput". Did you mean "UpdateUserDataInput", "UpdateBlockDataInput", "UpdateLetterDataInput", "CreateUserDataInput", or "UpdateUserInput"?
W20200217-12:33:30.482(0)? (STDERR)
W20200217-12:33:30.483(0)? (STDERR) Unknown type "LetterBlocksArticles". Did you mean "LetterBlocksSortInput", "LetterBlocks", "LetterBlocksFilterInput", "LetterSortInput", or "CreateLetterBlocksDataInput"?`

It looks like this is because create and update aren't supported. But there is still the error `Unknown type "LetterBlocksArticles"`

**Comment by GraemeFulton** [comment]
I just tried removing canCreate, and canUpdate from both subschemas, and adding blackbox to `articles.$` (as well as `blocks.$`):

```   
articles: {
      type: Array,
      canRead: ['guests'],
      group: articleGroup,
      optional: true,
      // canCreate: ['members'],
      // canUpdate: ['members'],
    },
    'articles.$': {
      type: articleSchema,
      blackbox: true,
    }
```
  blocks: {
    type: Array,
    canRead: ['guests'],
    group: blockGroup,
    optional: true,
    // canCreate: ['members'],
    // canUpdate: ['members'],
  },
  'blocks.$': {
    type: blockSchema,
        blackbox: true
  }
```
Now it works! Everything seems to be readable without a problem then, with the fragment defined the old way (just blocks, and not `blocks{articles}`:

```
name
blocks
date  
```

**Comment by eric-burel** [comment]
Thanks for the details I'll try to take a look at the failing case so they are at least clearer

**Comment by eric-burel** [comment]
Ok I think both `isIntl` and `isBlackbox` are too simplistic, they do not detect fields that array child of an intl field or blackboxed field. We will probably solve 2 issues at once with that

**Comment by eric-burel** [comment]
It's fixed on devel, you know should be able to only specify `blackbox` on the top most array field. Then array child block.$ will simply have type  JSON

**Comment by eric-burel** [comment]
@GraemeFulton let me know if there are other unexpected issues though, I only fixed the graphql generation bug so far (it won't create the faulty `LetterBlocksArticle` type anymore) but there might be other issue I did not expected

**Comment by eric-burel** [comment]
Aaaand solved for mutation types too, it now takes the blackbox into account. Your canUpdate in the child should be ignored instead of blatantly failing.
