### ISSUE TITLE
query option add args 'typeName'

### ISSUE THREAD

**Issue by gland2015** [VulcanJS/Vulcan#2557]
at useSingle， useMutil, useUpdate. useDelete, query option add args typeName，such as not need collection or collectionName... To reduce the introduction of collections

**Comment by eric-burel** [comment]
We will have to be cautious about `__typename` from graphql, maybe calling such fields `graphqlTypeName` or smth like that

**Comment by eric-burel** [comment]
New model in Vulcan NPM/Vulcan Next: we define Models, that are kind of lighter Collection. Models have a schema, but do not force you to have a corresponding mongo database or even to use graphql => you can spawn models on the fly without problem.

Passing typeName would be similar to working by reference : you need to maintain an object that maps the reference to their actual collection/model. We now tend to avoid this pattern, because it has the huge limitation of making dependencies between packages invisible and hard to manager. If you need to use a hook for a collection, it's normal that you import this collection.

One approach would be to export pre-made hooks in this case.
