### ISSUE TITLE
Invariant Violation - Could not find "client" in the context...

### ISSUE THREAD

**Issue by Kellokes** [VulcanJS/Vulcan#2584]
Hi all,

I tried several times to solve this problem, but found no solution.

I downloaded the latest version 1.15.0 of Vulcan via Git Clone and ran npm install, npm start on the terminal and the error Invariant Violation appeared for me.

![Captura de Tela 2020-06-08 às 13 48 47](https://user-images.githubusercontent.com/15666/84057923-d3146200-a98e-11ea-8041-d4fbc6c582f6.png)

I saw this problem here (https://github.com/apollographql/react-apollo/issues/3381), but I didn't understand how I can solve it.

**Comment by ErikDakoda** [comment]
The Vulcan repo is not meant to be run on its own - its a library of packages providing functionality for building web apps - but not a web app in itself. 

What you want to do is check out and run the Vulcan-Starter repo (https://github.com/VulcanJS/Vulcan-Starter), which contains several sample web apps. Here are the instructions:

https://docs.vulcanjs.org/index.html#Install

Then for contributing you can set up the Two-Repo Install:

https://docs.vulcanjs.org/index.html#Two-Repo-Install-Optional

**Comment by Kellokes** [comment]
Hi Erik,

Thanks to help me with my doubt. I did this steps of Vucaln-Start, but now I want to create my own app and I don´t know how I can remove the samples of Vulcan-Starter.

I thought that clone the latest version of vulcan.js repo I would be able to build an application from scratch and the error that I found trying to do this, seemed to me to be something that other people were experiencing as well.

By the way what the difference between common install and two repo Install?

Tks again!

**Comment by ErikDakoda** [comment]
You need to start with a clone of Vulcan-Starter to get your own web app going.

 * Just delete all subdirectories of `packages` except for `_boilerplate-generator`, `_buffer`, and `example-simple`
 * Open `meteor/packages` and make sure that under `Your Packages` only `example-simple` is uncommented (does not start with a #)
 * Execute npm run (which in turn executes `meteor --settings settings.json`)
 * Now you can add components and routes to define your pages

You only need the two-repo install if you want to contribute (make changes) to Vulcan. Otherwise, Meteor will automatically use the most recent version of the Vulcan packages published to Atmosphere, which is version 1.15.1 right now. In this configuration, the Vulcan repo you downloaded is not used at all.

**Comment by Kellokes** [comment]
Hello Erik, 

Thank you so much!

Your explanation was very enlightening, I believe it will help many Vulcan Js beginners as well.
